import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
  threeContainer: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    backgroundColor: "#1D1D1D",
    paddingTop: 20,
  },
  threeCardWrapper: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "flex-start",
    width: width * 0.95,
    height: height * 0.5,
    marginBottom: 20,
  },
  threeCardContainer: {
    width: width * 0.3,
    justifyContent: "flex-start",
    alignItems: "center",
    position: "relative",
  },
  threeCardName: {
    fontSize: 18,
    color: "#FFFFFF",
    textAlign: "center",
    marginTop: 10,
    width: "100%",
    fontFamily: "Cinzel-Decorative",
    marginBottom: 10,
    flexWrap: "wrap",
    height: 50,
  },
  threeCardNameBack: {
    fontSize: 18,
    color: "#FFFFFF",
    textAlign: "center",
    marginTop: 10,
    width: "100%",
    fontFamily: "Cinzel-Decorative",
    marginBottom: 10,
    flexWrap: "wrap",
    height: 50,
    opacity: 0,
  },
  threeCardImage: {
    width: "100%",
    height: 180,
    resizeMode: "contain",
    marginBottom: 30,
  },
  threeCardDescription: {
    fontSize: 14,
    color: "white",
    textAlign: "center",
    fontFamily: "serif",
    flexWrap: "wrap",
    lineHeight: 18,
    marginTop: 5,
    width: "100%",
    height: 350,
    overflow: "hidden",
  },
  threeCardDescriptionBack: {
    fontSize: 14,
    color: "white",
    textAlign: "center",
    fontFamily: "serif",
    flexWrap: "wrap",
    lineHeight: 18,
    marginTop: 5,
    width: "100%",
    height: 350,
    overflow: "hidden",
    opacity: 0,
  },
  threeButtonStyle: {
    backgroundColor: "#1C152A",
    padding: 10,
    borderRadius: 10,
    alignItems: "center",
    alignSelf: "center",
    marginTop: 75,
  },
  homebuttonStyle: {
    backgroundColor: "#1C152A",
    padding: 10,
    borderRadius: 10,
    alignItems: "center",
    margin: 10,
  },
  buttonHover: {
    backgroundColor: "#9543E8",
  },
  buttonText: {
    color: "white",
    fontSize: 16,
    marginHorizontal: 1,
    marginVertical: 1,
    fontFamily: "Cinzel-Decorative",
  },
});
